version: "3.3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    networks:
      - main
  eye_dota:
    image: eye_dota:v0.1
    container_name: eye_dota
    environment:
      MONGO: mongodb://root:secret@mongodb:27017
      MODEL_PATH: /tmp/models/total.keras
      SCALER_PATH: /tmp/models/total_scaler.joblib
      RIDGE_MODEL: /tmp/models/ridge_duration.joblib
      RIDGE_SCALER: /tmp/models/ridge_scaler.joblib
    ports:
      - "9090:9090"
    volumes:
      - ./eye_dota:/app
      - ./models:/tmp/models
    entrypoint: python3 main.py
    networks:
      - main
  frontend:
    build:
      context: .
      dockerfile: docker/front.Dockerfile
    container_name: frontend
    environment:
      FASTAPI: eye_dota
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - ./frontend:/app
    entrypoint: streamlit run main.py
    networks:
      - main

networks:
  main:
